name: cup

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [4096, 6]
      type: point_cloud
    agent_pos:
      shape: [21]
      type: low_dim
  action:
    shape: [21]


dataset:
  _target_: diffusion_policy_3d.dataset.r1_cup_dataset_3d.R1CupDataset3D
  zarr_path: data/cup_10ep_raw #NOTE: modeify this to 10ep or 1ep, or overwrite this in train_policy.sh
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 90
  agent_pos_noise_std: 0.01

  num_points: ${policy.pointcloud_encoder_cfg.num_points}
